# Generated by Django 4.1.4 on 2025-05-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('program', models.CharField(max_length=100, verbose_name='Образовательная программа')),
                ('course', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Курс')),
                ('group_number', models.CharField(max_length=10, verbose_name='Номер группы')),
                ('specialization', models.CharField(choices=[('intercultural', 'Межкультурная коммуникация'), ('teaching', 'Преподавание'), ('translation', 'Перевод')], max_length=20, verbose_name='Специализация')),
                ('graduation_year', models.IntegerField(verbose_name='Год окончания обучения')),
                ('average_grade', models.FloatField(verbose_name='Средний балл')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
